all : quicksortPthreads quicksortSequential

quicksortPthreads: quicksortPthreads.cpp
	g++ -std=c++11 -o quicksortPthreads quicksortPthreads.cpp -lpthread

quicksortSequential: quicksortSequential.cpp
	g++ -std=c++11 -o quicksortSequential quicksortSequential.cpp 
